apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-ui
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-ui
  template:
    metadata:
      labels:
        app: ecommerce-ui
    spec:
      containers:
        - name: ecommerce-ui
          image: olymahmudmugdho/cne-ecommerce-ui:437090b71a2e5ee6d9a10585e0f17599ea2deeb3
          ports:
            - containerPort: 4173
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
