apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-ui
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-ui
  template:
    metadata:
      labels:
        app: ecommerce-ui
    spec:
      containers:
        - name: ecommerce-ui
          image: olymahmudmugdho/cne-ecommerce-ui:b25756cd55420a4fc0984c8fdb4ca96e69a626ab
          ports:
            - containerPort: 4173
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
