apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: olymahmudmugdho/inventory-service:8abc07da40f0a6a332b7679d36e91d771da30d12
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
