apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: olymahmudmugdho/inventory-service:25fa6833a778809f1e2951da7a43df3b8ebf9234
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
