apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: olymahmudmugdho/inventory-service:d3442a0ffe8f1c543f73c323784b9f9d40f0847a
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
