apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: olymahmudmugdho/order-service:8abc07da40f0a6a332b7679d36e91d771da30d12
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
