apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: olymahmudmugdho/order-service:a926f4f6d91eaddb2a8d62d4dd6c07c5d782cc0d
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
