apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: olymahmudmugdho/order-service:437090b71a2e5ee6d9a10585e0f17599ea2deeb3
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
