apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: olymahmudmugdho/order-service:b25756cd55420a4fc0984c8fdb4ca96e69a626ab
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
