apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: olymahmudmugdho/product-service:abe2fd1fa7592d0298986e966d843cfe842beb76
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
