apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: olymahmudmugdho/product-service:10bbe9a576c547be0d515d4f3273e024678745f7
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
